### ISSUE TITLE
Optional: Use link which google fonts provide.

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/elena-landing#3]
https://github.com/IgnatSemchuk/elena/blob/master/css/style.css#L2
Check Network panel - you do multiple requests 

![image](https://user-images.githubusercontent.com/8848858/46913408-01ad2000-cf95-11e8-9fc4-c25cba1db38e.png)

You can decrese them to one request.

**Comment by IgnatSemchuk** [comment]
done. Have made one request
